# Google App Engine configuration
runtime: python312

# Instance class (F1 = 256MB RAM, F2 = 512MB, F4 = 1GB, F4_1G = 2GB)
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1

# Environment variables (use Secret Manager for sensitive data)
env_variables:
  PYTHONUNBUFFERED: "1"

# Entrypoint
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

# Handlers for static files (optional)
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
