-- Schema for YouTube RAG Backend
-- Run this in your Supabase SQL editor to create the necessary tables

-- Enable pgvector extension for vector operations
CREATE EXTENSION IF NOT EXISTS vector;

-- Table to track video processing status
CREATE TABLE IF NOT EXISTS video_status (
    video_id TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('processing', 'active')),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for faster status lookups
CREATE INDEX IF NOT EXISTS idx_video_status_video_id ON video_status(video_id);

-- Table to store video embeddings with chunks
CREATE TABLE IF NOT EXISTS video_embeddings (
    id BIGSERIAL PRIMARY KEY,
    video_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector(3072),  -- Gemini embedding-001 produces 3072-dimensional vectors
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(video_id, chunk_index)
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_video_embeddings_video_id ON video_embeddings(video_id);
CREATE INDEX IF NOT EXISTS idx_video_embeddings_expiry ON video_embeddings(expiry_date);
-- Note: Vector indexes (ivfflat/hnsw) have a 2000 dimension limit in pgvector
-- Since gemini-embedding-001 produces 3072 dimensions, we'll do similarity search in application code
-- This is fine for smaller datasets. For production scale, consider using a dedicated vector DB or smaller embeddings.

-- Function to automatically delete expired embeddings
CREATE OR REPLACE FUNCTION delete_expired_embeddings()
RETURNS void AS $$
BEGIN
    DELETE FROM video_embeddings WHERE expiry_date < NOW();
END;
$$ LANGUAGE plpgsql;

-- Optional: Create a scheduled job to run cleanup daily
-- Note: This requires pg_cron extension to be enabled in Supabase
-- SELECT cron.schedule('cleanup-expired-embeddings', '0 2 * * *', 'SELECT delete_expired_embeddings()');

-- Grant necessary permissions
ALTER TABLE video_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_embeddings ENABLE ROW LEVEL SECURITY;

-- Create policies (adjust based on your authentication setup)
-- For now, allowing all authenticated users to read/write
CREATE POLICY "Allow all operations on video_status"
    ON video_status
    FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow all operations on video_embeddings"
    ON video_embeddings
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE video_status IS 'Tracks the processing status of YouTube videos';
COMMENT ON TABLE video_embeddings IS 'Stores text chunks and their embeddings from YouTube video transcripts';
COMMENT ON COLUMN video_embeddings.embedding IS 'Vector embedding generated by Gemini embedding-001 (3072 dimensions)';
COMMENT ON COLUMN video_embeddings.expiry_date IS 'Timestamp when this embedding should be deleted (default: 1 day from creation)';
